[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Scheduled function for daily cleanup at midnight UTC
[[plugins]]
  package = "@netlify/plugin-scheduled-functions"

[plugins.inputs]
  cron = "0 0 * * *"  # Daily at midnight UTC
  path = "/.netlify/edge-functions/daily-cleanup"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"